# Generated by Django 2.2 on 2019-09-20 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20190920_0635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'permissions': (('add_only_10_notes', 'To provide 10 notes facility'), ('add_only_20_notes', 'To provide 20 notes facility'))},
        ),
    ]
