# Generated by Django 2.2 on 2019-09-23 06:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20190916_0609'),
        ('notes', '0006_custnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='custnote',
            name='Plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.Plan'),
        ),
        migrations.AddField(
            model_name='custnote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custnote',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='custnote',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='custnote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
