# Generated by Django 2.2 on 2019-09-23 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20190923_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='User',
        ),
    ]
