# Generated by Django 2.2 on 2019-09-24 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_remove_notes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custnote',
            name='Plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.UserPlan'),
        ),
    ]
