# Generated by Django 2.2 on 2019-09-16 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('sub_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('plan_type', models.CharField(choices=[('FREE', 'Free Plan'), ('MONTHLY_BASIC', 'Monthly Basic ($15/Mo)'), ('MONTHLY_PRO', 'Monthly Pro ($30/Mo)'), ('ANNUAL_PRO', 'Annual Pro ($300/Yr)')], default='FREE', max_length=15)),
                ('initiated_on', models.DateTimeField(blank=True, null=True)),
                ('terminated_on', models.DateTimeField(blank=True, null=True)),
                ('customer_id', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='subscription.Customer')),
            ],
        ),
    ]
