# Generated by Django 2.2 on 2019-09-23 06:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20190916_0609'),
        ('tasks', '0005_custtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='custtask',
            name='Plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.Plan'),
        ),
        migrations.AddField(
            model_name='custtask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 9, 23, 6, 16, 38, 288688, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custtask',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='custtask',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='custtask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
