# Generated by Django 2.2 on 2019-09-23 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20190923_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='User',
        ),
    ]
