# Generated by Django 2.2 on 2019-09-24 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_tasks_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custtask',
            name='Plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.UserPlan'),
        ),
    ]
